### ISSUE TITLE
docker file is 6 months out-of-date, leading to build and security issues

### ISSUE THREAD

**Issue by nealmcb** [sequenceiq/docker-pam#3]
Can you re-build this on some sort of regular basis so we can avoid build and security issues?

E.g. when I try to `apt-get install ipython-notebook` on your great spark:1.2.0-ubuntu image, which is built FROM this one (indirectly), it fails, and I have to do an apt-get update first:

....
Get:23 http://archive.ubuntu.com/ubuntu/ trusty/main python-pkg-resources all 3.3-1ubuntu1 [61.9 kB]
Err http://archive.ubuntu.com/ubuntu/ trusty-security/main libcurl3-gnutls amd64 7.35.0-1ubuntu2.2
  404  Not Found [IP: 91.189.91.15 80]

**Comment by akanto** [comment]
Thanks. I have added a yum update and apt-get update/upgrade into the Dockefiles and re-triggered the build. It takes some time to rebuild all images that are based on this image.

Unfortunately I do not see any option on Docker Hub to set up a periodic automatic build.

**Comment by nealmcb** [comment]
Thanks!

Rather than a periodic rebuild, I think what we would want is a rebuild of an image when an image it depends on is updated.  This is trickier with images like Ubuntu which incorporate so many underlying packages, updates etc.  Perhaps if there were Ubuntu tags for major security fixes, or for monthly upgrades or the like? Would it be possible in Docker to trigger an image build when a new tag comes out for a dependency?  I'm not sure what the right approach is....

**Comment by akanto** [comment]
The problem is that the Centos 6.5 and Ubuntu 14.04 is not really changing for example if I get the latest Centos 6.5 then right now, then it shall have exactly the same package versions what it had a half year ago or what it had when the Centos 6.5 was released. The only thing what makes a bit difference that I put the the yum update in the beginning of Dockerfile which will download the updates/fixes during every build on the top of 6.5.

In case of Ubuntu, there is a 14.04 and also a 14.04.1 tag, but the Dockerfile is referencing 14.04 and we need a manual step to change the Dockerfile from 14.04 to  14.04.1. But I believe that the apt-get update + upgrade on 14.04  will bring the image to the same state.

Depending on centos:latest is not an option in our case. I agree that periodic builds are usually not the best solution, but in this case I don't really see any other way.

**Comment by nealmcb** [comment]
Ahh - interesting.  I saw that there was a recent 14.04-related image on Hub, but that was probably just 14.04.1.  Thanks again for doing the apt-get yourselves.  And I do wonder if there is a better way for Ubuntu and its downstreams to deal with this in general.
